apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mythical-db-pvc
  namespace: benson
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client