apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-api
  namespace: benson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mythical-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mythical-api
    spec:
      initContainers:
        - name: init-seed-images
          image: ${DOCKERHUB_USERNAME}/mythical_inventory_images:6
          command:
            [
              "sh",
              "-c",
              'echo "Files in /app/images:"; ls -l /app/images; echo "Files in /seededImages:"; ls -l /seededImages; if [ -z "$(ls -A /app/images)" ]; then cp -r /seededImages/* /app/images/; fi; echo "After copying, files in /app/images:"; ls -l /app/images',
            ]
          volumeMounts:
            - name: images-storage
              mountPath: /app/images
      containers:
        - name: mythical-api
          image: ${DOCKERHUB_USERNAME}/mythical_api:${IMAGE_TAG}
          env:
            - name: PG_DB
              value: ${PG_DB}
            - name: PG_USER
              value: ${PG_USER}
            - name: PG_PASSWORD
              value: ${PG_PASSWORD}
            - name: PG_HOST
              value: mythical-db-svc
            - name: PG_PORT
              value: "5432"
            - name: PATH_TO_IMAGES
              value: "/app/images"
            - name: ALLOW_LOCALHOST
              value: "false"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: images-storage
              mountPath: /app/images
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: images-storage
          persistentVolumeClaim:
            claimName: mythical-img-pvc
