name: Deployment the Client to server 2
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/client.yml
  workflow_dispatch:
jobs:
  node-build-lint-test:
    runs-on: [self-hosted, benson]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          cd ./client
          npm ci
          cd ..

      - name: Build the client
        run: |
          cd ./client
          npm run build
          cd ..
        continue-on-error: false

      - name: Run Linter
        run: |
          cd ./client
          npm run lint
          cd ..
        continue-on-error: false

      - name: Run tests
        run: |
          cd ./client
          npm run test
          cd ..
        continue-on-error: false

  build-and-push:
    runs-on: [self-hosted, benson]
    needs: node-build-lint-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mythical_client:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/mythical_client:${{ github.run_number }} ./client
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/mythical_client

      - name: Deploy to Kubernetes
        run: |
          export PATH=$PATH:~.nix-profile/bin:/nix/var/nix/profiles/default/bin
          export IMAGE_TAG=${{ github.run_number }}
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          kubectl get namespace benson || kubectl create namespace benson

          for file in client/kube/*; do 
              cat "$file" | envsubst | kubectl apply -f -; 
          done
